# Generated by Django 3.2.11 on 2022-03-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220308_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ariticle',
            new_name='Article',
        ),
    ]
